### ISSUE TITLE
Hello,  Why does this dislocation occur ？ Javascript Error: Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by tangafa** [maximtrp/tmplot#7] opened 2022-08-20 14:38 UTC
![image](https://user-images.githubusercontent.com/42071222/185751811-9e3f7c79-ad4f-430b-bd01-63aafe2565c4.png)

**Comment by maximtrp** [comment] 2022-08-20 15:03
Hey! Are you using MS Windows?

**Comment by maximtrp** [comment] 2022-08-25 07:23
I could not reproduce this bug. Could you please tell what versions of Altair and JupyterLab you are using? I suppose you have successfully updated tmplot to 0.0.9. Also, what OS are you using?

**Comment by maximtrp** [comment] 2022-09-05 14:35
@mlabussiere Thank you! What about tmplot v0.0.8?

**Comment by maximtrp** [comment] 2022-09-05 14:53
@mlabussiere Could you please try to use JupyterLab instead of Jupyter Notebook?

**Comment by mlabussiere** [comment] 2022-09-05 15:02
With tmplot v.0.0.8 I get the error "_ValueError: perplexity must be less than n_samples" when I run tmp.report(model=model, docs=texts)

**Comment by mlabussiere** [comment] 2022-09-05 15:06
With JupyterLab and v.0.0.8 I obtain the same error message 
![github_tmplot3](https://user-images.githubusercontent.com/95632080/188478117-b8ccb3eb-cb58-4d4d-9dd7-6b16ca36307a.png)

**Comment by mlabussiere** [comment] 2022-09-05 15:21
WIth JupyterLab and v.0.0.9 I do not get any error message but I doubt this is the expected result 
![github_tmplot4](https://user-images.githubusercontent.com/95632080/188480464-b2620bf8-4328-4543-a959-083f233689e5.png)
When I click on the link, I only get the plot for term probabilities.

**Comment by maximtrp** [comment] 2022-09-05 15:50
Thank you! I am still trying to reproduce this error. What version of JupyterLab do you have?

**Comment by mlabussiere** [comment] 2022-09-05 15:58
This is JupyterLab version 3.0.14

**Comment by maximtrp** [comment] 2022-09-05 17:09
I have pushed a fix. Please try it:

```bash
pip install git+https://github.com/maximtrp/tmplot
```

I also suggest to update JupyterLab to some recent version (v.3.4.6, for example).

```bash
pip install -U jupyterlab
```

**Comment by mlabussiere** [comment] 2022-09-06 11:18
@maximtrp This seems to work now! Many thanks for your quick fix!

**Comment by mlabussiere** [comment] 2022-09-06 12:52
Edit: this seems to work on Jupyter Notebook only. I do not get any error message on JupyterLab (updated to 3.3.2), but I obtain the same output as yesterday: the link points either to the plot for term probabilities or the scatter plot for topics (without me deciding), but I cannot have both. 

> WIth JupyterLab and v.0.0.9 I do not get any error message but I doubt this is the expected result ![github_tmplot4](https://user-images.githubusercontent.com/95632080/188480464-b2620bf8-4328-4543-a959-083f233689e5.png) When I click on the link, I only get the plot for term probabilities.

**Comment by maximtrp** [comment] 2022-09-06 13:11
@mlabussiere  Thank you for the feedback! Have you updated JupyterLab? Could you please create new environment for tmplot using `venv`?

```bash
python -m venv venv
```

**Comment by mlabussiere** [comment] 2022-09-06 13:15
I updated JupyterLab to 3.3.2.

**Comment by mlabussiere** [comment] 2022-09-06 15:29
> @mlabussiere Thank you for the feedback! Have you updated JupyterLab? Could you please create new environment for tmplot using `venv`?
> 
> ```shell
> python -m venv venv
> ```

Let you know as soon as I figure out how to do that ;)

**Comment by maximtrp** [comment] 2022-09-06 17:35
@mlabussiere  Just run this command in your command line:

```bash
python -m venv venv
```

**Comment by mlabussiere** [comment] 2022-09-07 14:03
@maximtrp the thing is that I am using Anaconda and that python is not recognized by my command prompt. Anaconda is defined as my default Python and it has its own virtual environments...I am struggling to juggle the two.
I ran your script in JupyterLab using a new Anaconda environment for bitermplus and tmplot though, and I got the same result as before: the interactive report does not display as it should.

**Comment by jeanbaptisteb** [comment] 2022-09-07 14:06
> @mlabussiere I have pushed a fix. Please try it:
> 
> ```shell
> pip install git+https://github.com/maximtrp/tmplot
> ```
> 
> I also suggest to update JupyterLab to some recent version (v.3.4.6, for example).
> 
> ```shell
> pip install -U jupyterlab
> ```

@maximtrp FYI, I had this problem ("Javascript Error: Cannot read properties of undefined (reading 'forEach')") on a Jupyter notebook with a version of tmplot I installed a few days ago through pip. However, good news, your fix (`pip install git+https://github.com/maximtrp/tmplot`) does work :) So, thanks! 

If it can somehow help, I'm under Windows 10 64 bits, Python 3.10.2, Jupyter Notebook 6.4.12, JupyterLab 3.4.6. 

Here are the detailed steps I took for installing the fix, if it can help others (quite basic and simple to do, but you never know): I shut down Jupyter notebook, then I uninstalled tmplot in my virtual environment (venv) by running `pip uninstall tmplot`, and finally I used `pip install git+https://github.com/maximtrp/tmplot` in the same venv. Then, I restarted the notebook, and now the "Intertopic distance plot" works properly without message errors.

**Comment by mlabussiere** [comment] 2022-09-07 15:00
> @maximtrp the thing is that I am using Anaconda and that python is not recognized by my command prompt. Anaconda is defined as my default Python and it has its own virtual environments...I am struggling to juggle the two. I ran your script in JupyterLab using a new Anaconda environment for bitermplus and tmplot though, and I got the same result as before: the interactive report does not display as it should.

Fyi here's the environment 
[new_env.txt](https://github.com/maximtrp/tmplot/files/9507293/new_env.txt)

**Comment by maximtrp** [comment] 2022-09-08 05:59
@jeanbaptisteb Thank you for suggesting help and instructions! I hope the issue @mlabussiere is facing will resolve soon.

@mlabussiere Please try this piece of code before accessing tmplot `report`:
```python
import altair as alt
alt.renderers.enable('default')
```

This is strange: I do not see Altair in the list of packages for your environment. It should be there as it is a direct dependency of tmplot.

**Comment by mlabussiere** [comment] 2022-09-08 11:16
Hi @maximtrp, indeed I also found it strange that Altair does not seems to be installed and I already added the piece of code you mention when trying to solve the JavaScript error message. But I had inserted it at the beginning of the script. If I insert it right before calling report, this works properly! 

Just fyi and don't know if it's relevant, but there's the following warning when I install tmplot in a new environment (with only Python + gensim previously installed). 
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyldavis 3.3.1 requires future, which is not installed.
pyldavis 3.3.1 requires numexpr, which is not installed.
```

**Comment by maximtrp** [comment] 2022-09-08 11:59
@mlabussiere Thank you for the feedback!
I suggest that you [create a new conda environment](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) and log every step in the console (it is better to have separate envs for various tasks). Please install only needed packages. Then create the list of installed packages and test everything in Jupyter.

**Comment by mlabussiere** [comment] 2022-09-08 14:56
@maximtrp That's actually what I did previously. I created a new conda environment and only installed tmplot and bitermplus. Altair is not part of the installed packages (see attached log).
[new_env_withoutaltair.txt](https://github.com/maximtrp/tmplot/files/9527955/new_env_withoutaltair.txt)

**Closed** 2023-09-11 05:31 UTC
Labels: bug
